# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Plone package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plone-version:
          - "Plone61"
        python-version: [3.11, 3.13]

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/uv
          key: ${{ runner.os }}-tox-${{ matrix.python-version }}-${{ matrix.plone-version }}-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/*.cfg') }}-${{ hashFiles('**/constraints.txt') }}-${{ hashFiles('**/tox.ini') }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create a custom plonex file
        run: |
          echo "---" > etc/plonex.local.yml
          echo "plone_version: '${{ matrix.plone-version }}-latest'" >> etc/plonex.local.yml
          echo "python: 'python${{ matrix.python-version }}'" >> etc/plonex.local.yml

      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run the tests
        run: |
          make test
